// <auto-generated />
namespace ProyectoXalli_Gentelella.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TablaMoneda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TablaMoneda));
        
        string IMigrationMetadata.Id
        {
            get { return "202011021713299_TablaMoneda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
